services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    restart: unless-stopped

  auth:
    build:
      context: ./src/service-auth
      dockerfile: Dockerfile
    container_name: auth-service
    env_file: ./.env.auth
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    restart: unless-stopped

  api-gateway:
    build:
      context: ./src/service-api-gateway
    container_name: api-gateway
    env_file: ./.env.gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
    restart: unless-stopped

  ws-broker:
    build:
      context: ./src/service-ws-broker
    container_name: ws-broker
    env_file: ./.env.ws
    ports:
      - "8081:8081"

    restart: unless-stopped
  controller:
    build:
      context: ./src/service-controller
    container_name: controller
    env_file: ./.env.controller
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - /mnt/openhvx:/share:ro   # <-- partage SMB monté sur l’hôte → visible dans le container
    restart: unless-stopped

volumes:
  mongo_data:
