services:

  traefik:
    image: traefik:v3.1
    user: "0:0"
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///run/podman/podman.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=internal
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --api.dashboard=false
      # logs
      - --log.level=DEBUG
      - --log.filePath=/var/log/traefik/traefik.log
      - --accesslog=true
      - --accesslog.filePath=/var/log/traefik/access.log
      - --accesslog.bufferingsize=0
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers.defaultmode=keep
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /run/podman/podman.sock:/run/podman/podman.sock:ro,z
      - ./.traefik/dynamic:/etc/traefik/dynamic:ro
      - ./.traefik/certs:/etc/traefik/certs:ro
      - ./.traefik/logs:/var/log/traefik 
    networks:
      - public
      - internal
    restart: unless-stopped
    security_opt:
      - label=disable


  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - internal
      - public
    ports:
      - "5672:5672" 
      - "15672:15672"
    restart: unless-stopped

  auth:
    build:
      context: ./src/service-auth
      dockerfile: Dockerfile
    container_name: auth-service
    env_file: ./.env.auth
    depends_on:
      - mongo
    networks:
      - internal
    restart: unless-stopped

  api-gateway:
    build:
      context: ./src/service-api-gateway
    container_name: api-gateway
    env_file: ./.env.gateway
    depends_on:
      - auth
    networks:
      - internal
    restart: unless-stopped
    labels:
      - traefik.enable=true

      # TENANT
      - traefik.http.routers.api.rule=Host(`api.openhvx.local`) && PathPrefix(`/api/v1/tenant`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.middlewares=cors-auth@file,rate-tenant@file,sec-headers@file,compress@file
      - traefik.http.routers.api.service=tenant-svc
      - traefik.http.services.tenant-svc.loadbalancer.server.port=8080
      - traefik.docker.network=internal

      # ADMIN
      - traefik.http.routers.admin.rule=Host(`admin-api.openhvx.local`) && PathPrefix(`/api/v1/admin`)
      - traefik.http.routers.admin.entrypoints=websecure
      - traefik.http.routers.admin.tls=true
      - traefik.http.routers.admin.middlewares=cors-auth@file,rate-admin@file,sec-headers@file,compress@file
      - traefik.http.routers.admin.service=admin-svc
      - traefik.http.services.admin-svc.loadbalancer.server.port=8080

      # CONSOLE (Browser)
      - traefik.http.routers.console.rule=Host(`console.openhvx.local`) && PathPrefix(`/api/v1/console`)
      - traefik.http.routers.console.entrypoints=websecure
      - traefik.http.routers.console.tls=true
      - traefik.http.routers.console.middlewares=sec-headers@file,compress@file
      - traefik.http.routers.console.service=console-svc
      - traefik.http.services.console-svc.loadbalancer.server.port=8080
      - traefik.docker.network=internal


  ws-broker:
    build:
      context: ./src/service-ws-broker
    container_name: ws-broker
    env_file: ./.env.ws
    networks:
      - internal
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=internal

      # AGENTS → ws-broker (direct)
      - traefik.http.routers.wsb.rule=Host(`ws.openhvx.local`) && PathPrefix(`/ws/`)
      - traefik.http.routers.wsb.entrypoints=websecure
      - traefik.http.routers.wsb.tls=true
      - traefik.http.routers.wsb.middlewares=sec-headers@file,compress@file
      - traefik.http.routers.wsb.service=wsb-svc
      - traefik.http.services.wsb-svc.loadbalancer.server.port=8081

  controller:
    build:
      context: ./src/service-controller
    container_name: controller
    env_file: ./.env.controller
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - /mnt/openhvx:/share:ro
    networks:
      - internal
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  public:
    driver: bridge
    name: public
  internal:
    driver: bridge
    internal: true 
    name: internal